# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  meili:
    image: getmeili/meilisearch:v0.27.2
    environment:
      MEILI_MASTER_KEY: MASTER_KEY
    volumes:
      - ./meili_data:/meili_data
    ports:
      - 7700:7700
