# Use postgres/example user/password credentials
version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  meilisearch:
    image: getmeili/meilisearch:v0.27.2
    environment:
      MEILI_MASTER_KEY: MASTER_KEY
    volumes:
      - ./data/meilisearch:/meili_data
    ports:
      - 7700:7700
